const frameLayer=document.getElementById('frameLayer');
const frameSvg=document.getElementById('frameSvg');
const particles=document.getElementById('particles');
const titleMain=document.getElementById('titleMain');
const titleRow=document.getElementById('titleRow');
const subLayer=document.getElementById('subLayer');
const pickLike=document.getElementById('pickLike');
const pickBell=document.getElementById('pickBell');
const bottomBar=document.getElementById('bottomBar');
const eqWrap=document.getElementById('eqWrap');
function baseFrame(c,sub,cornerFn){return `<defs><linearGradient id="fg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${c}" stop-opacity="0.9"/><stop offset="50%" stop-color="${c}" stop-opacity="0.6"/><stop offset="100%" stop-color="${c}" stop-opacity="0.8"/></linearGradient><filter id="sf"><feGaussianBlur stdDeviation="0.7"/></filter></defs><rect x="16" y="16" width="868" height="474" rx="2" stroke="url(#fg)" stroke-width="0.6" opacity="0.35"/><rect x="26" y="26" width="848" height="454" rx="1" stroke="url(#fg)" stroke-width="1.5" opacity="0.8"/><rect x="36" y="36" width="828" height="434" rx="1" stroke="${sub}" stroke-width="0.5" opacity="0.5"/>${cornerFn()}<line x1="180" y1="26" x2="720" y2="26" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/><line x1="180" y1="480" x2="720" y2="480" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/>`;}
function buildGuitarFrame(){const c='#c89040',cs='rgba(200,150,60,0.28)';const corner=()=>`<g filter="url(#sf)">${[['26,26','1,1'],['874,26','-1,1'],['26,480','1,-1'],['874,480','-1,-1']].map(([t,s],i)=>`<g transform="translate(${t}) scale(${s})"><path d="M0,70 L0,0 L70,0" stroke="${c}" stroke-width="1.5" fill="none" opacity="0.7" stroke-linecap="round"/><path d="M8,55 L8,8 L55,8" stroke="${c}" stroke-width="0.7" fill="none" opacity="0.4"/><circle cx="20" cy="45" r="5" fill="${c}" opacity="${i<2?.65:.45}"/><line x1="25" y1="45" x2="25" y2="28" stroke="${c}" stroke-width="1.5" opacity="0.6"/><circle cx="38" cy="32" r="4.5" fill="${c}" opacity="${i<2?.6:.4}"/><line x1="42.5" y1="32" x2="42.5" y2="16" stroke="${c}" stroke-width="1.5" opacity="0.55"/></g>`).join('')}</g>`;return baseFrame(c,cs,corner);}
function buildGuitarParticles(layer){layer.innerHTML='';const notes=['♩','♪','♫','♬'];for(let i=0;i<12;i++){const el=document.createElement('div');const size=10+Math.random()*12,dur=7+Math.random()*8,del=-(Math.random()*dur),x=Math.random()*100,op=.12+Math.random()*.22,sx=(Math.random()-.5)*70;el.style.cssText=`position:absolute;left:${x}%;top:-20px;font-size:${size}px;color:#c89040;opacity:${op};animation:guitarNote${i} ${dur}s ${del}s linear infinite;pointer-events:none;`;el.innerHTML=`<style>@keyframes guitarNote${i}{0%{transform:translateY(-20px) translateX(0);opacity:0;}8%{opacity:${op};}88%{opacity:${op};}100%{transform:translateY(540px) translateX(${sx}px);opacity:0;}}</style>${notes[i%4]}`;layer.appendChild(el);}}
function buildGuitarEq(){const svgW=100,svgH=48,strings=6,colors=['#d4a843','#c89830','#b88420','#a87010','#987000','#886000'],durs=[.22,.28,.19,.34,.25,.31],amps=[7,5.5,8,4.5,6.5,5];let svg=`<svg width="${svgW}" height="${svgH}" viewBox="0 0 ${svgW} ${svgH}"><rect x="0" y="0" width="${svgW}" height="${svgH}" rx="4" fill="rgba(28,16,6,0.6)" stroke="rgba(180,130,40,0.3)" stroke-width="1"/>`;for(let i=0;i<strings;i++){const y=(i+1)*(svgH/(strings+1)),an=`gs${i}`,amp=amps[i],mid=svgW/2,thick=.8+i*.22;svg+=`<style>@keyframes ${an}{0%{d:path("M 0 ${y} Q ${mid} ${y-amp} ${svgW} ${y}");}50%{d:path("M 0 ${y} Q ${mid} ${y+amp} ${svgW} ${y}");}100%{d:path("M 0 ${y} Q ${mid} ${y-amp*.4} ${svgW} ${y}");}}</style><path d="M 0 ${y} Q ${mid} ${y-amp} ${svgW} ${y}" stroke="${colors[i]}" stroke-width="${thick}" fill="none" opacity="0.88" style="animation:${an} ${durs[i]}s ease-in-out infinite;"/>`;}return svg+'</svg>';}
function clearState(){frameLayer.classList.remove('show','hide');titleMain.classList.remove('show','hide');titleRow.classList.remove('show','hide');subLayer.classList.remove('show','hide');bottomBar.classList.remove('show');pickLike.classList.remove('active');pickBell.classList.remove('active');}
function applyPhase(t){clearState();if(t>=.4&&t<10)frameLayer.classList.add('show');if(t>=1&&t<5){titleMain.classList.add('show');titleRow.classList.add('show');}else if(t>=5){titleMain.classList.add('hide');titleRow.classList.add('hide');}if(t>=5&&t<10){subLayer.classList.add('show');pickLike.classList.add('active');pickBell.classList.add('active');}else if(t>=10){subLayer.classList.add('hide');}if(t>=10)bottomBar.classList.add('show');}
function loop(){const start=performance.now();function tick(now){applyPhase(((now-start)/1000)%12);requestAnimationFrame(tick);}requestAnimationFrame(tick);}
frameSvg.innerHTML=buildGuitarFrame();buildGuitarParticles(particles);eqWrap.innerHTML=buildGuitarEq();loop();
