const frameLayer=document.getElementById('frameLayer');
const frameSvg=document.getElementById('frameSvg');
const particles=document.getElementById('particles');
const titleMain=document.getElementById('titleMain');
const titleRow=document.getElementById('titleRow');
const subLayer=document.getElementById('subLayer');
const starLike=document.getElementById('starLike');
const starBell=document.getElementById('starBell');
const bottomBar=document.getElementById('bottomBar');
const eqWrap=document.getElementById('eqWrap');
function baseFrame(c,sub,cornerFn){return `<defs><linearGradient id="fg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${c}" stop-opacity="0.9"/><stop offset="50%" stop-color="${c}" stop-opacity="0.6"/><stop offset="100%" stop-color="${c}" stop-opacity="0.8"/></linearGradient><filter id="sf"><feGaussianBlur stdDeviation="0.7"/></filter></defs><rect x="16" y="16" width="868" height="474" rx="2" stroke="url(#fg)" stroke-width="0.6" opacity="0.35"/><rect x="26" y="26" width="848" height="454" rx="1" stroke="url(#fg)" stroke-width="1.5" opacity="0.8"/><rect x="36" y="36" width="828" height="434" rx="1" stroke="${sub}" stroke-width="0.5" opacity="0.5"/>${cornerFn()}<line x1="180" y1="26" x2="720" y2="26" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/><line x1="180" y1="480" x2="720" y2="480" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/>`;}
function starSvg(x,y,size,op,c='#b090e8'){const pts=[];for(let i=0;i<10;i++){const angle=i*(Math.PI/5)-Math.PI/2;const r=i%2===0?size:size*.4;pts.push(`${x+Math.cos(angle)*r},${y+Math.sin(angle)*r}`);}return `<polygon points="${pts.join(' ')}" fill="${c}" opacity="${op}"/><circle cx="${x}" cy="${y}" r="${size*.15}" fill="white" opacity="${op*.7}"/>`;}
function buildStarFrame(){const c='#b090e8',cs='rgba(160,130,220,0.28)';const corner=()=>`<g filter="url(#sf)">${starSvg(40,40,16,.7)}${starSvg(68,26,11,.58)}${starSvg(26,68,11,.58)}${starSvg(58,55,8,.48)}${starSvg(26,44,7,.4)}<g transform="translate(900,0) scale(-1,1)">${starSvg(40,40,16,.7)}${starSvg(68,26,11,.58)}${starSvg(58,55,8,.48)}</g><g transform="translate(0,506) scale(1,-1)">${starSvg(40,40,13,.58)}${starSvg(26,68,9,.48)}</g><g transform="translate(900,506) scale(-1,-1)">${starSvg(40,40,13,.58)}${starSvg(26,68,9,.48)}</g></g>`;return baseFrame(c,cs,corner);}
function buildStarParticles(layer){layer.innerHTML='';for(let i=0;i<22;i++){const el=document.createElement('div');const size=5+Math.random()*8;const x=Math.random()*100;const y=Math.random()*100;const dur=1.2+Math.random()*2.8;const del=-(Math.random()*dur);const rot=Math.random()*360;const op=.25+Math.random()*.45;el.style.cssText=`position:absolute;left:${x}%;top:${y}%;opacity:${op};pointer-events:none;animation:starTwinkle${i} ${dur}s ${del}s ease-in-out infinite;`;el.innerHTML=`<style>@keyframes starTwinkle${i}{0%,100%{transform:scale(.55) rotate(${rot}deg);opacity:${op*.35};}50%{transform:scale(1.15) rotate(${rot+60}deg);opacity:${op};}}</style><svg width="${size*2.6}" height="${size*2.6}" viewBox="0 0 26 26">${starSvg(13,13,size,0.9,'#b090e8')}</svg>`;layer.appendChild(el);}}
function eqBase(count,colW,maxH,shapeFn){const d=[.42,.57,.36,.63,.44,.52,.38,.66,.46,.54,.40],s=[.28,.44,.20,.50,.32,.46,.22,.54,.36,.40,.26];let svg=`<svg width="${count*colW}" height="${maxH}" viewBox="0 0 ${count*colW} ${maxH}" overflow="visible">`;for(let i=0;i<count;i++){const x=i*colW+colW/2,an=`eqStar${i}`;svg+=`<style>@keyframes ${an}{0%{transform:scaleY(${s[i]}) translateY(${maxH*(1-s[i])*.5}px);}100%{transform:scaleY(1) translateY(0);}}</style><g style="animation:${an} ${d[i]}s ease-in-out infinite alternate;transform-origin:bottom center;transform-box:fill-box;">${shapeFn(x,maxH,i)}</g>`;}return svg+'</svg>';}
function buildStarEq(){return eqBase(11,12,48,(x,H,i)=>{const size=4+(i%3);const y=H/2;return `${starSvg(x,y,size,.82,`hsl(${260+i*6},65%,${58+i*2}%)`)}<line x1="${x}" y1="${y+size}" x2="${x}" y2="${H}" stroke="rgba(176,144,232,0.35)" stroke-width="1"/>`;});}
function clearState(){frameLayer.classList.remove('show','hide');titleMain.classList.remove('show','hide');titleRow.classList.remove('show','hide');subLayer.classList.remove('show','hide');bottomBar.classList.remove('show');starLike.classList.remove('active');starBell.classList.remove('active');}
function applyPhase(t){clearState();if(t>=.4&&t<10)frameLayer.classList.add('show');if(t>=1&&t<5){titleMain.classList.add('show');titleRow.classList.add('show');}else if(t>=5){titleMain.classList.add('hide');titleRow.classList.add('hide');}if(t>=5&&t<10){subLayer.classList.add('show');starLike.classList.add('active');starBell.classList.add('active');}else if(t>=10){subLayer.classList.add('hide');}if(t>=10)bottomBar.classList.add('show');}
function loop(){const start=performance.now();function tick(now){applyPhase(((now-start)/1000)%12);requestAnimationFrame(tick);}requestAnimationFrame(tick);}
frameSvg.innerHTML=buildStarFrame();buildStarParticles(particles);eqWrap.innerHTML=buildStarEq();loop();
