const frameLayer=document.getElementById('frameLayer');
const frameSvg=document.getElementById('frameSvg');
const particles=document.getElementById('particles');
const titleMain=document.getElementById('titleMain');
const titleRow=document.getElementById('titleRow');
const subLayer=document.getElementById('subLayer');
const heartPath=document.getElementById('heartPath');
const bellG=document.getElementById('bellG');
const bottomBar=document.getElementById('bottomBar');
const eqWrap=document.getElementById('eqWrap');
function baseFrame(c,sub,cornerSvg){return `<defs><linearGradient id="fg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${c}" stop-opacity="0.9"/><stop offset="100%" stop-color="${c}" stop-opacity="0.65"/></linearGradient><filter id="sf"><feGaussianBlur stdDeviation="0.7"/></filter></defs><rect x="16" y="16" width="868" height="474" rx="2" stroke="url(#fg)" stroke-width="0.6" opacity="0.32"/><rect x="26" y="26" width="848" height="454" rx="1" stroke="url(#fg)" stroke-width="1.5" opacity="0.78"/><rect x="36" y="36" width="828" height="434" rx="1" stroke="${sub}" stroke-width="0.5" opacity="0.45"/>${cornerSvg}<line x1="180" y1="26" x2="720" y2="26" stroke="url(#fg)" stroke-width="0.5" opacity="0.28"/><line x1="180" y1="480" x2="720" y2="480" stroke="url(#fg)" stroke-width="0.5" opacity="0.28"/>`;}
function buildCoffeeFrame(){const c='#b87840';const cup=(tx,ty,sx,sy)=>`<g transform="translate(${tx},${ty}) scale(${sx},${sy})" filter="url(#sf)"><path d="M8,30 Q10,50 20,52 Q30,50 32,30 Z" stroke="${c}" stroke-width="1.2" fill="none" opacity="0.65"/><path d="M32,38 Q42,38 42,44 Q42,50 32,48" stroke="${c}" stroke-width="1" fill="none" opacity="0.5"/><line x1="8" y1="54" x2="32" y2="54" stroke="${c}" stroke-width="1.5" opacity="0.55"/><path d="M14,24 Q16,16 14,8" stroke="${c}" stroke-width="0.8" fill="none" opacity="0.38" stroke-dasharray="2,2"/><path d="M20,24 Q24,12 20,4" stroke="${c}" stroke-width="0.8" fill="none" opacity="0.32" stroke-dasharray="2,2"/><path d="M26,24 Q28,16 26,8" stroke="${c}" stroke-width="0.8" fill="none" opacity="0.28" stroke-dasharray="2,2"/></g>`;return baseFrame(c,'rgba(185,120,60,0.28)',cup(26,26,1,1)+cup(874,26,-1,1)+cup(26,506,-1,-1)+cup(874,506,1,-1));}
function buildCoffeeParticles(layer){layer.innerHTML='';for(let i=0;i<10;i++){const el=document.createElement('div');const x=10+Math.random()*80,dur=3+Math.random()*3,del=-(Math.random()*dur);el.style.cssText=`position:absolute;left:${x}%;bottom:60px;pointer-events:none;`;el.innerHTML=`<svg width="20" height="60"><path d="M10,60 Q${4+Math.random()*12},40 10,20 Q${4+Math.random()*12},10 10,0" stroke="rgba(185,140,80,0.18)" stroke-width="1.5" fill="none"><animate attributeName="opacity" values="0;0.5;0" dur="${dur}s" begin="${del}s" repeatCount="indefinite"/><animateTransform attributeName="transform" type="translate" values="0,0;${(Math.random()-0.5)*8},0" dur="${dur}s" begin="${del}s" repeatCount="indefinite"/></path></svg>`;layer.appendChild(el);}}
function eqBase(count,colW,maxH,shapeFn){const D=[.42,.57,.36,.63,.44,.52,.38,.66,.46,.54,.40],S=[.28,.44,.20,.50,.32,.46,.22,.54,.36,.40,.26];let svg=`<svg width="${count*colW}" height="${maxH}" viewBox="0 0 ${count*colW} ${maxH}" overflow="visible">`;for(let i=0;i<count;i++){const x=i*colW+colW/2,an=`eqCoffee${i}`;svg+=`<style>@keyframes ${an}{0%{transform:scaleY(${S[i]}) translateY(${maxH*(1-S[i])*.5}px)}100%{transform:scaleY(1) translateY(0)}}</style><g style="animation:${an} ${D[i]}s ease-in-out infinite alternate;transform-origin:bottom center;transform-box:fill-box">${shapeFn(x,maxH,i)}</g>`;}return svg+'</svg>';}
function buildCoffeeEq(){return eqBase(10,13,48,(x,H,i)=>{const c=`hsl(${28+i*5},${65+i*2}%,${35+i*3}%)`;return `<path d="M${x},${H} Q${x-5},${H-H*.6} ${x},${H-H*.85} Q${x+5},${H-H*.6} ${x},${H}Z" fill="${c}" opacity="0.78"/><ellipse cx="${x}" cy="${H-H*.85}" rx="3" ry="2" fill="${c}" opacity="0.5"/>`;});}
function clearState(){frameLayer.classList.remove('show','hide');titleMain.classList.remove('show','hide');titleRow.classList.remove('show','hide');subLayer.classList.remove('show','hide');bottomBar.classList.remove('show');heartPath.classList.remove('draw');bellG.classList.remove('ring');}
function applyPhase(t){clearState();if(t>=.4&&t<10)frameLayer.classList.add('show');if(t>=1&&t<5){titleMain.classList.add('show');titleRow.classList.add('show');}else if(t>=5){titleMain.classList.add('hide');titleRow.classList.add('hide');}if(t>=5&&t<10){subLayer.classList.add('show');heartPath.classList.add('draw');bellG.classList.add('ring');}else if(t>=10){subLayer.classList.add('hide');}if(t>=10)bottomBar.classList.add('show');}
function loop(){const start=performance.now();function tick(now){applyPhase(((now-start)/1000)%12);requestAnimationFrame(tick)}requestAnimationFrame(tick)}
frameSvg.innerHTML=buildCoffeeFrame();buildCoffeeParticles(particles);eqWrap.innerHTML=buildCoffeeEq();loop();
