const frameLayer=document.getElementById('frameLayer');
const frameSvg=document.getElementById('frameSvg');
const particles=document.getElementById('particles');
const titleMain=document.getElementById('titleMain');
const titleRow=document.getElementById('titleRow');
const subLayer=document.getElementById('subLayer');
const heartPath=document.getElementById('heartPath');
const bellG=document.getElementById('bellG');
const bottomBar=document.getElementById('bottomBar');
const eqWrap=document.getElementById('eqWrap');
function baseFrame(c,sub,cornerSvg){return `<defs><linearGradient id="fg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${c}" stop-opacity="0.9"/><stop offset="100%" stop-color="${c}" stop-opacity="0.65"/></linearGradient><filter id="sf"><feGaussianBlur stdDeviation="0.7"/></filter></defs><rect x="16" y="16" width="868" height="474" rx="2" stroke="url(#fg)" stroke-width="0.6" opacity="0.32"/><rect x="26" y="26" width="848" height="454" rx="1" stroke="url(#fg)" stroke-width="1.5" opacity="0.78"/><rect x="36" y="36" width="828" height="434" rx="1" stroke="${sub}" stroke-width="0.5" opacity="0.45"/>${cornerSvg}<line x1="180" y1="26" x2="720" y2="26" stroke="url(#fg)" stroke-width="0.5" opacity="0.28"/><line x1="180" y1="480" x2="720" y2="480" stroke="url(#fg)" stroke-width="0.5" opacity="0.28"/>`;}
function buildBookFrame(){const c='#a08050';const corner=(tx,ty,sx,sy)=>`<g transform="translate(${tx},${ty}) scale(${sx},${sy})" filter="url(#sf)"><rect x="0" y="0" width="60" height="8" rx="2" fill="${c}" opacity="0.45"/><rect x="0" y="0" width="8" height="60" rx="2" fill="${c}" opacity="0.45"/><rect x="4" y="4" width="45" height="5" rx="1.5" fill="${c}" opacity="0.28"/><rect x="4" y="4" width="5" height="45" rx="1.5" fill="${c}" opacity="0.28"/><path d="M12,12 Q28,8 44,16 Q52,22 48,36 Q40,48 26,44 Q10,38 12,24 Q14,16 22,14" stroke="${c}" stroke-width="0.8" fill="none" opacity="0.38"/></g>`;return baseFrame(c,'rgba(160,128,80,0.25)',corner(26,26,1,1)+corner(874,26,-1,1)+corner(26,480,1,-1)+corner(874,480,-1,-1));}
function buildBookParticles(layer){layer.innerHTML='';for(let i=0;i<15;i++){const el=document.createElement('div');const s=3+Math.random()*5,x=Math.random()*100,dur=8+Math.random()*10,del=-(Math.random()*dur),sx=(Math.random()-0.5)*60,rot=(Math.random()-0.5)*90;el.style.cssText=`position:absolute;left:${x}%;top:-10px;opacity:0;animation:bookDust${i} ${dur}s ${del}s linear infinite;pointer-events:none;`;el.innerHTML=`<style>@keyframes bookDust${i}{0%{opacity:0;transform:translateY(-10px) rotate(0deg)}10%{opacity:.35}85%{opacity:.25}100%{opacity:0;transform:translateY(530px) translateX(${sx}px) rotate(${rot}deg)}}</style><svg width="${s*3}" height="${s*2}" viewBox="0 0 15 8"><rect x="0" y="0" width="15" height="8" rx="1" fill="rgba(200,170,110,0.6)"/><line x1="0" y1="3" x2="15" y2="3" stroke="rgba(150,120,70,0.4)" stroke-width="0.5"/></svg>`;layer.appendChild(el);}}
function eqBase(count,colW,maxH,shapeFn){const D=[.42,.57,.36,.63,.44,.52,.38,.66,.46,.54,.40],S=[.28,.44,.20,.50,.32,.46,.22,.54,.36,.40,.26];let svg=`<svg width="${count*colW}" height="${maxH}" viewBox="0 0 ${count*colW} ${maxH}" overflow="visible">`;for(let i=0;i<count;i++){const x=i*colW+colW/2,an=`eqBook${i}`;svg+=`<style>@keyframes ${an}{0%{transform:scaleY(${S[i]}) translateY(${maxH*(1-S[i])*.5}px)}100%{transform:scaleY(1) translateY(0)}}</style><g style="animation:${an} ${D[i]}s ease-in-out infinite alternate;transform-origin:bottom center;transform-box:fill-box">${shapeFn(x,maxH,i)}</g>`;}return svg+'</svg>';}
function buildBookEq(){return eqBase(10,13,48,(x,H,i)=>{const c=`hsl(${32+i*3},${48+i*3}%,${36+i*2}%)`;return `<rect x="${x-4.5}" y="0" width="9" height="${H}" rx="1.5" fill="${c}" opacity="0.72"/><rect x="${x-5}" y="0" width="10" height="4" rx="1" fill="${c}" opacity="0.9"/><rect x="${x-5}" y="${H-4}" width="10" height="4" rx="1" fill="${c}" opacity="0.9"/><line x1="${x}" y1="6" x2="${x}" y2="${H-6}" stroke="rgba(255,220,160,0.2)" stroke-width="0.5"/>`;});}
function clearState(){frameLayer.classList.remove('show','hide');titleMain.classList.remove('show','hide');titleRow.classList.remove('show','hide');subLayer.classList.remove('show','hide');bottomBar.classList.remove('show');heartPath.classList.remove('draw');bellG.classList.remove('ring');}
function applyPhase(t){clearState();if(t>=.4&&t<10)frameLayer.classList.add('show');if(t>=1&&t<5){titleMain.classList.add('show');titleRow.classList.add('show');}else if(t>=5){titleMain.classList.add('hide');titleRow.classList.add('hide');}if(t>=5&&t<10){subLayer.classList.add('show');heartPath.classList.add('draw');bellG.classList.add('ring');}else if(t>=10){subLayer.classList.add('hide');}if(t>=10)bottomBar.classList.add('show');}
function loop(){const start=performance.now();function tick(now){applyPhase(((now-start)/1000)%12);requestAnimationFrame(tick)}requestAnimationFrame(tick)}
frameSvg.innerHTML=buildBookFrame();buildBookParticles(particles);eqWrap.innerHTML=buildBookEq();loop();
