const frameLayer=document.getElementById('frameLayer');
const frameSvg=document.getElementById('frameSvg');
const particles=document.getElementById('particles');
const titleMain=document.getElementById('titleMain');
const titleRow=document.getElementById('titleRow');
const subLayer=document.getElementById('subLayer');
const snowLike=document.getElementById('snowLike');
const snowBell=document.getElementById('snowBell');
const bottomBar=document.getElementById('bottomBar');
const eqWrap=document.getElementById('eqWrap');
function baseFrame(c,sub,cornerFn){return `<defs><linearGradient id="fg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${c}" stop-opacity="0.9"/><stop offset="50%" stop-color="${c}" stop-opacity="0.6"/><stop offset="100%" stop-color="${c}" stop-opacity="0.8"/></linearGradient><filter id="sf"><feGaussianBlur stdDeviation="0.7"/></filter></defs><rect x="16" y="16" width="868" height="474" rx="2" stroke="url(#fg)" stroke-width="0.6" opacity="0.35"/><rect x="26" y="26" width="848" height="454" rx="1" stroke="url(#fg)" stroke-width="1.5" opacity="0.8"/><rect x="36" y="36" width="828" height="434" rx="1" stroke="${sub}" stroke-width="0.5" opacity="0.5"/>${cornerFn()}<line x1="180" y1="26" x2="720" y2="26" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/><line x1="180" y1="480" x2="720" y2="480" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/>`;}
function buildSnowFrame(){const c='#90c0e8',cs='rgba(140,195,240,0.28)';const flake=(x,y,size,op)=>{let lines='';for(let a=0;a<6;a++){const angle=a*Math.PI/3;const ex=x+Math.cos(angle)*size,ey=y+Math.sin(angle)*size;const mx=x+Math.cos(angle)*size*.5,my=y+Math.sin(angle)*size*.5;lines+=`<line x1="${x}" y1="${y}" x2="${ex}" y2="${ey}" stroke="${c}" stroke-width="1" opacity="${op}"/><line x1="${mx}" y1="${my}" x2="${mx+Math.cos(angle+Math.PI/4)*size*.25}" y2="${my+Math.sin(angle+Math.PI/4)*size*.25}" stroke="${c}" stroke-width="0.8" opacity="${op*.7}"/><line x1="${mx}" y1="${my}" x2="${mx+Math.cos(angle-Math.PI/4)*size*.25}" y2="${my+Math.sin(angle-Math.PI/4)*size*.25}" stroke="${c}" stroke-width="0.8" opacity="${op*.7}"/>`;}return lines+`<circle cx="${x}" cy="${y}" r="${size*.12}" fill="${c}" opacity="${op}"/>`;};const corner=()=>`<g filter="url(#sf)">${flake(46,46,18,.65)}${flake(72,26,14,.55)}${flake(26,72,14,.55)}${flake(26,40,10,.45)}<g transform="translate(900,0) scale(-1,1)">${flake(46,46,18,.65)}${flake(72,26,14,.55)}${flake(26,40,10,.45)}</g><g transform="translate(0,506) scale(1,-1)">${flake(46,46,15,.55)}${flake(26,72,12,.45)}</g><g transform="translate(900,506) scale(-1,-1)">${flake(46,46,15,.55)}${flake(26,72,12,.45)}</g></g>`;return baseFrame(c,cs,corner);}
function buildSnowParticles(layer){layer.innerHTML='';for(let i=0;i<25;i++){const el=document.createElement('div');const size=3+Math.random()*7,dur=5+Math.random()*9,del=-(Math.random()*dur),x=Math.random()*100,sx=(Math.random()-.5)*50,op=.3+Math.random()*.5;el.style.cssText=`position:absolute;left:${x}%;top:-20px;opacity:0;animation:snowFall${i} ${dur}s ${del}s linear infinite;pointer-events:none;`;el.innerHTML=`<style>@keyframes snowFall${i}{0%{opacity:0;transform:translateY(-20px) translateX(0) rotate(0deg);}10%{opacity:${op};}85%{opacity:${op};}100%{opacity:0;transform:translateY(540px) translateX(${sx}px) rotate(${360*Math.random()}deg);}}</style><svg width="${size*2}" height="${size*2}" viewBox="0 0 16 16"><circle cx="8" cy="8" r="${size*.6}" fill="#c0e0ff" opacity="0.9"/><circle cx="8" cy="8" r="${size*.25}" fill="white" opacity="0.8"/></svg>`;layer.appendChild(el);}}
function eqBase(count,colW,maxH,shapeFn){const d=[.42,.57,.36,.63,.44,.52,.38,.66,.46,.54,.40],s=[.28,.44,.20,.50,.32,.46,.22,.54,.36,.40,.26];let svg=`<svg width="${count*colW}" height="${maxH}" viewBox="0 0 ${count*colW} ${maxH}" overflow="visible">`;for(let i=0;i<count;i++){const x=i*colW+colW/2,an=`eqSnow${i}`;svg+=`<style>@keyframes ${an}{0%{transform:scaleY(${s[i]}) translateY(${maxH*(1-s[i])*.5}px);}100%{transform:scaleY(1) translateY(0);}}</style><g style="animation:${an} ${d[i]}s ease-in-out infinite alternate;transform-origin:bottom center;transform-box:fill-box;">${shapeFn(x,maxH,i)}</g>`;}return svg+'</svg>';}
function buildSnowEq(){return eqBase(11,12,48,(x,H,i)=>{const arms=6,size=5+i%3;let lines='';for(let a=0;a<arms;a++){const ang=a*Math.PI/3;lines+=`<line x1="${x}" y1="${H/2}" x2="${x+Math.cos(ang)*size}" y2="${H/2+Math.sin(ang)*size}" stroke="#90c0e8" stroke-width="1.2" opacity="0.75"/>`;}return lines+`<circle cx="${x}" cy="${H/2}" r="2" fill="#c0e4ff" opacity="0.85"/><line x1="${x}" y1="${H/2+size}" x2="${x}" y2="${H}" stroke="rgba(144,192,232,0.3)" stroke-width="1"/>`;});}
function clearState(){frameLayer.classList.remove('show','hide');titleMain.classList.remove('show','hide');titleRow.classList.remove('show','hide');subLayer.classList.remove('show','hide');bottomBar.classList.remove('show');snowLike.classList.remove('active');snowBell.classList.remove('active');}
function applyPhase(t){clearState();if(t>=.4&&t<10)frameLayer.classList.add('show');if(t>=1&&t<5){titleMain.classList.add('show');titleRow.classList.add('show');}else if(t>=5){titleMain.classList.add('hide');titleRow.classList.add('hide');}if(t>=5&&t<10){subLayer.classList.add('show');snowLike.classList.add('active');snowBell.classList.add('active');}else if(t>=10){subLayer.classList.add('hide');}if(t>=10)bottomBar.classList.add('show');}
function loop(){const start=performance.now();function tick(now){applyPhase(((now-start)/1000)%12);requestAnimationFrame(tick);}requestAnimationFrame(tick);}
frameSvg.innerHTML=buildSnowFrame();buildSnowParticles(particles);eqWrap.innerHTML=buildSnowEq();loop();
