const frameLayer=document.getElementById('frameLayer');
const frameSvg=document.getElementById('frameSvg');
const particles=document.getElementById('particles');
const titleMain=document.getElementById('titleMain');
const titleRow=document.getElementById('titleRow');
const subLayer=document.getElementById('subLayer');
const brushLike=document.getElementById('brushLike');
const brushBell=document.getElementById('brushBell');
const bottomBar=document.getElementById('bottomBar');
const eqWrap=document.getElementById('eqWrap');

function buildBambooFrame(){
  const c='#8aaa80';
  const seg=(x,y,h)=>`<rect x="${x}" y="${y}" width="8" height="${h-3}" rx="2" fill="${c}" opacity="0.55"/><rect x="${x-1}" y="${y+h-4}" width="10" height="4" rx="1.5" fill="${c}" opacity="0.75"/><path d="M${x+8},${y+h*.4} Q${x+22},${y+h*.3} ${x+28},${y+h*.5}" stroke="${c}" stroke-width="1.2" fill="none" opacity="0.5"/><path d="M${x+8},${y+h*.7} Q${x-6},${y+h*.6} ${x-12},${y+h*.75}" stroke="${c}" stroke-width="1" fill="none" opacity="0.4"/>`;
  const corner=`<g filter="url(#sf)"><g transform="translate(22,26)">${seg(0,0,32)}${seg(0,32,30)}${seg(0,62,28)}${seg(14,10,30)}${seg(14,40,28)}</g><g transform="translate(878,26) scale(-1,1)">${seg(0,0,32)}${seg(0,32,30)}${seg(14,10,30)}</g><g transform="translate(22,480) scale(1,-1)">${seg(0,0,28)}${seg(0,28,26)}${seg(14,8,26)}</g><g transform="translate(878,480) scale(-1,-1)">${seg(0,0,28)}${seg(14,8,26)}</g></g>`;
  return `<defs><linearGradient id="fg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${c}" stop-opacity="0.9"/><stop offset="50%" stop-color="${c}" stop-opacity="0.6"/><stop offset="100%" stop-color="${c}" stop-opacity="0.8"/></linearGradient><filter id="sf"><feGaussianBlur stdDeviation="0.7"/></filter></defs><rect x="16" y="16" width="868" height="474" rx="2" stroke="url(#fg)" stroke-width="0.6" opacity="0.35"/><rect x="26" y="26" width="848" height="454" rx="1" stroke="url(#fg)" stroke-width="1.5" opacity="0.8"/><rect x="36" y="36" width="828" height="434" rx="1" stroke="rgba(140,175,130,0.25)" stroke-width="0.5" opacity="0.5"/>${corner}<line x1="180" y1="26" x2="720" y2="26" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/><line x1="180" y1="480" x2="720" y2="480" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/>`;
}
function buildBambooParticles(layer){layer.innerHTML='';for(let i=0;i<8;i++){const el=document.createElement('div');const x=5+Math.random()*90;const size=10+Math.random()*8;const dur=3+Math.random()*4;const del=-(Math.random()*dur);const sx=(Math.random()-.5)*60;el.style.cssText=`position:absolute;left:${x}%;top:-30px;opacity:0;animation:leafFall${i} ${dur}s ${del}s linear infinite;pointer-events:none;`;el.innerHTML=`<style>@keyframes leafFall${i}{0%{opacity:0;transform:translateY(-20px) rotate(0deg);}10%{opacity:0.6;}85%{opacity:0.5;}100%{opacity:0;transform:translateY(540px) translateX(${sx}px) rotate(${(Math.random()-.5)*120}deg);}}</style><svg width="${size}" height="${size*.5}" viewBox="0 0 20 10"><ellipse cx="10" cy="5" rx="9" ry="4.5" fill="#8aaa80" opacity="0.8"/><line x1="1" y1="5" x2="19" y2="5" stroke="#6a8a60" stroke-width="0.8" opacity="0.5"/></svg>`;layer.appendChild(el);}}
function eqBase(count,colW,maxH,shapeFn){const d=[0.42,0.57,0.36,0.63,0.44,0.52,0.38,0.66,0.46];const s=[0.28,0.44,0.20,0.50,0.32,0.46,0.22,0.54,0.36];let svg=`<svg width="${count*colW}" height="${maxH}" viewBox="0 0 ${count*colW} ${maxH}" overflow="visible">`;for(let i=0;i<count;i++){const x=i*colW+colW/2;const an=`eqBamboo${i}`;svg+=`<style>@keyframes ${an}{0%{transform:scaleY(${s[i]}) translateY(${maxH*(1-s[i])*.5}px);}100%{transform:scaleY(1) translateY(0);}}</style><g style="animation:${an} ${d[i]}s ease-in-out infinite alternate;transform-origin:bottom center;transform-box:fill-box;">${shapeFn(x,maxH,i)}</g>`;}return svg+'</svg>';}
function buildBambooEq(){return eqBase(8,15,48,(x,H,i)=>{const c=`hsl(${115+i*5},40%,${38+i*4}%)`;let out='';const segs=4,sh=H/segs;for(let j=0;j<segs;j++){const y=H-(j+1)*sh;out+=`<rect x="${x-4}" y="${y}" width="8" height="${sh-3}" rx="1.5" fill="${c}" opacity="${0.6+j*.08}"/><rect x="${x-5}" y="${y+sh-4}" width="10" height="4" rx="1.5" fill="${c}" opacity="0.85"/>`;}out+=`<path d="M${x+4},${H*.35} Q${x+18},${H*.22} ${x+24},${H*.32}" stroke="${c}" stroke-width="1.2" fill="none" opacity="0.55"/>`;return out;});}
function clearState(){frameLayer.classList.remove('show','hide');titleMain.classList.remove('show','hide');titleRow.classList.remove('show','hide');subLayer.classList.remove('show','hide');bottomBar.classList.remove('show');brushLike.classList.remove('draw');brushBell.classList.remove('draw');}
function applyPhase(t){clearState();if(t>=.4&&t<10)frameLayer.classList.add('show');if(t>=1&&t<5){titleMain.classList.add('show');titleRow.classList.add('show');}else if(t>=5){titleMain.classList.add('hide');titleRow.classList.add('hide');}if(t>=5&&t<10){subLayer.classList.add('show');brushLike.classList.add('draw');brushBell.classList.add('draw');}else if(t>=10){subLayer.classList.add('hide');}if(t>=10)bottomBar.classList.add('show');}
function loop(){const cycle=12;const start=performance.now();function tick(now){const t=((now-start)/1000)%cycle;applyPhase(t);requestAnimationFrame(tick);}requestAnimationFrame(tick);}
frameSvg.innerHTML=buildBambooFrame();buildBambooParticles(particles);eqWrap.innerHTML=buildBambooEq();loop();
