const frameLayer=document.getElementById('frameLayer');
const frameSvg=document.getElementById('frameSvg');
const particles=document.getElementById('particles');
const titleMain=document.getElementById('titleMain');
const titleRow=document.getElementById('titleRow');
const subLayer=document.getElementById('subLayer');
const roseLike=document.getElementById('roseLike');
const roseBell=document.getElementById('roseBell');
const bottomBar=document.getElementById('bottomBar');
const eqWrap=document.getElementById('eqWrap');
function baseFrame(c,sub,cornerFn){return `<defs><linearGradient id="fg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${c}" stop-opacity="0.9"/><stop offset="50%" stop-color="${c}" stop-opacity="0.6"/><stop offset="100%" stop-color="${c}" stop-opacity="0.8"/></linearGradient><filter id="sf"><feGaussianBlur stdDeviation="0.7"/></filter></defs><rect x="16" y="16" width="868" height="474" rx="2" stroke="url(#fg)" stroke-width="0.6" opacity="0.35"/><rect x="26" y="26" width="848" height="454" rx="1" stroke="url(#fg)" stroke-width="1.5" opacity="0.8"/><rect x="36" y="36" width="828" height="434" rx="1" stroke="${sub}" stroke-width="0.5" opacity="0.5"/>${cornerFn()}<line x1="180" y1="26" x2="720" y2="26" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/><line x1="180" y1="480" x2="720" y2="480" stroke="url(#fg)" stroke-width="0.5" opacity="0.3"/>`;}
function buildRoseFrame(){const c='#c83040',cs='rgba(200,60,80,0.28)';const petal=(cx,cy,rx,ry,rot,op)=>`<ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" fill="${c}" opacity="${op}" transform="rotate(${rot},${cx},${cy})"/>`;const rose=(x,y,size,op)=>`${petal(x,y,size,size*.6,0,op)}${petal(x,y,size,size*.6,72,op)}${petal(x,y,size,size*.6,144,op)}${petal(x,y,size,size*.6,216,op)}${petal(x,y,size,size*.6,288,op)}<circle cx="${x}" cy="${y}" r="${size*.3}" fill="#ff9090" opacity="${op*.8}"/>`;const corner=()=>`<g filter="url(#sf)"><path d="M26,90 Q44,52 76,26" stroke="${c}" stroke-width="1.2" opacity="0.55" fill="none"/><path d="M26,60 Q52,38 80,26" stroke="${c}" stroke-width="0.8" opacity="0.38" fill="none"/>${rose(42,70,8,.7)}${rose(56,50,9,.72)}${rose(70,34,8,.68)}${rose(78,26,7,.65)}<g transform="translate(900,0) scale(-1,1)"><path d="M26,90 Q44,52 76,26" stroke="${c}" stroke-width="1.2" opacity="0.55" fill="none"/>${rose(42,70,8,.7)}${rose(56,50,9,.72)}${rose(70,34,8,.68)}${rose(78,26,7,.65)}</g><g transform="translate(0,506) scale(1,-1)"><path d="M26,90 Q44,52 76,26" stroke="${c}" stroke-width="1.2" opacity="0.5" fill="none"/>${rose(42,70,7,.6)}${rose(70,34,7,.58)}</g><g transform="translate(900,506) scale(-1,-1)"><path d="M26,90 Q44,52 76,26" stroke="${c}" stroke-width="1.2" opacity="0.5" fill="none"/>${rose(42,70,7,.6)}${rose(70,34,7,.58)}</g></g>`;return baseFrame(c,cs,corner);}
function buildRoseParticles(layer){layer.innerHTML='';const colors=['#c83040','#d84858','#e86070','#f07888'];for(let i=0;i<16;i++){const el=document.createElement('div');const size=6+Math.random()*8,dur=7+Math.random()*7,del=-(Math.random()*dur),x=Math.random()*100,sx=(Math.random()-.5)*90,r0=Math.random()*360,op=.3+Math.random()*.4,c=colors[i%4];el.style.cssText=`position:absolute;left:${x}%;top:-20px;opacity:0;animation:roseFall${i} ${dur}s ${del}s linear infinite;pointer-events:none;`;el.innerHTML=`<style>@keyframes roseFall${i}{0%{opacity:0;transform:translateY(-20px) rotate(${r0}deg);}8%{opacity:${op};}88%{opacity:${op};}100%{opacity:0;transform:translateY(540px) translateX(${sx}px) rotate(${r0+200}deg);}}</style><svg width="${size*2}" height="${size*2}" viewBox="0 0 20 20"><ellipse cx="10" cy="10" rx="8" ry="5" fill="${c}" opacity="0.85" transform="rotate(0 10 10)"/><ellipse cx="10" cy="10" rx="8" ry="5" fill="${c}" opacity="0.7" transform="rotate(60 10 10)"/><ellipse cx="10" cy="10" rx="8" ry="5" fill="${c}" opacity="0.75" transform="rotate(120 10 10)"/><circle cx="10" cy="10" r="2.5" fill="#ff9090" opacity="0.8"/></svg>`;layer.appendChild(el);}}
function eqBase(count,colW,maxH,shapeFn){const d=[.42,.57,.36,.63,.44,.52,.38,.66,.46,.54],s=[.28,.44,.20,.50,.32,.46,.22,.54,.36,.40];let svg=`<svg width="${count*colW}" height="${maxH}" viewBox="0 0 ${count*colW} ${maxH}" overflow="visible">`;for(let i=0;i<count;i++){const x=i*colW+colW/2,an=`eqRose${i}`;svg+=`<style>@keyframes ${an}{0%{transform:scaleY(${s[i]}) translateY(${maxH*(1-s[i])*.5}px);}100%{transform:scaleY(1) translateY(0);}}</style><g style="animation:${an} ${d[i]}s ease-in-out infinite alternate;transform-origin:bottom center;transform-box:fill-box;">${shapeFn(x,maxH,i)}</g>`;}return svg+'</svg>';}
function buildRoseEq(){return eqBase(10,13,46,(x,H,i)=>{const c=`hsl(${350+i*4},68%,${42+i*2}%)`;return `${[0,72,144,216,288].map(a=>`<ellipse cx="${x}" cy="${H/2}" rx="4.5" ry="${H*.42}" fill="${c}" opacity="0.6" transform="rotate(${a},${x},${H/2})"><animateTransform attributeName="transform" type="rotate" from="${a} ${x} ${H/2}" to="${a+360} ${x} ${H/2}" dur="${2+i*.25}s" repeatCount="indefinite" additive="replace"/></ellipse>`).join('')}<circle cx="${x}" cy="${H/2}" r="2.5" fill="#ff8890" opacity="0.8"/>`;});}
function clearState(){frameLayer.classList.remove('show','hide');titleMain.classList.remove('show','hide');titleRow.classList.remove('show','hide');subLayer.classList.remove('show','hide');bottomBar.classList.remove('show');roseLike.classList.remove('active');roseBell.classList.remove('active');}
function applyPhase(t){clearState();if(t>=.4&&t<10)frameLayer.classList.add('show');if(t>=1&&t<5){titleMain.classList.add('show');titleRow.classList.add('show');}else if(t>=5){titleMain.classList.add('hide');titleRow.classList.add('hide');}if(t>=5&&t<10){subLayer.classList.add('show');roseLike.classList.add('active');roseBell.classList.add('active');}else if(t>=10){subLayer.classList.add('hide');}if(t>=10)bottomBar.classList.add('show');}
function loop(){const start=performance.now();function tick(now){applyPhase(((now-start)/1000)%12);requestAnimationFrame(tick);}requestAnimationFrame(tick);}
frameSvg.innerHTML=buildRoseFrame();buildRoseParticles(particles);eqWrap.innerHTML=buildRoseEq();loop();
