const frameLayer=document.getElementById('frameLayer');
const frameSvg=document.getElementById('frameSvg');
const particles=document.getElementById('particles');
const titleMain=document.getElementById('titleMain');
const titleRow=document.getElementById('titleRow');
const subLayer=document.getElementById('subLayer');
const tapeLike=document.getElementById('tapeLike');
const tapeBell=document.getElementById('tapeBell');
const bottomBar=document.getElementById('bottomBar');
const eqWrap=document.getElementById('eqWrap');
function baseFrame(c,sub,cornerSvg){return `<defs><linearGradient id="fg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${c}" stop-opacity="0.9"/><stop offset="100%" stop-color="${c}" stop-opacity="0.65"/></linearGradient><filter id="sf"><feGaussianBlur stdDeviation="0.7"/></filter></defs><rect x="16" y="16" width="868" height="474" rx="2" stroke="url(#fg)" stroke-width="0.6" opacity="0.32"/><rect x="26" y="26" width="848" height="454" rx="1" stroke="url(#fg)" stroke-width="1.5" opacity="0.78"/><rect x="36" y="36" width="828" height="434" rx="1" stroke="${sub}" stroke-width="0.5" opacity="0.45"/>${cornerSvg}<line x1="180" y1="26" x2="720" y2="26" stroke="url(#fg)" stroke-width="0.5" opacity="0.28"/><line x1="180" y1="480" x2="720" y2="480" stroke="url(#fg)" stroke-width="0.5" opacity="0.28"/>`;}
function buildCassetteFrame(){const c='#c8a040';const reel=(tx,ty,sx,sy)=>`<g transform="translate(${tx},${ty}) scale(${sx},${sy})"><circle cx="20" cy="20" r="18" stroke="${c}" stroke-width="1.2" fill="none" opacity="0.55"/><circle cx="20" cy="20" r="10" stroke="${c}" stroke-width="0.8" fill="none" opacity="0.4"/><circle cx="20" cy="20" r="4" fill="${c}" opacity="0.5"/>${[0,60,120,180,240,300].map(a=>`<line x1="20" y1="20" x2="${20+14*Math.cos(a*Math.PI/180)}" y2="${20+14*Math.sin(a*Math.PI/180)}" stroke="${c}" stroke-width="0.8" opacity="0.35"/>`).join('')}</g>`;return baseFrame(c,'rgba(200,160,60,0.28)',reel(26,26,1,1)+reel(854,26,-1,1)+reel(26,466,1,-1)+reel(854,466,-1,-1));}
function buildCassetteParticles(layer){layer.innerHTML='';for(let i=0;i<30;i++){const el=document.createElement('div');const s=1+Math.random()*3,x=Math.random()*100,y=Math.random()*100,dur=.5+Math.random()*1.5,del=-(Math.random()*dur);el.style.cssText=`position:absolute;left:${x}%;top:${y}%;pointer-events:none;`;el.innerHTML=`<svg width="${s*3}" height="${s*3}"><circle cx="${s*1.5}" cy="${s*1.5}" r="${s}" fill="rgba(200,170,100,0.4)"><animate attributeName="opacity" values="0;0.5;0" dur="${dur}s" begin="${del}s" repeatCount="indefinite"/></circle></svg>`;layer.appendChild(el);}const scan=document.createElement('div');scan.className='scanline';layer.appendChild(scan);}
function eqBase(count,colW,maxH,shapeFn){const D=[.42,.57,.36,.63,.44,.52,.38,.66,.46,.54,.40],S=[.28,.44,.20,.50,.32,.46,.22,.54,.36,.40,.26];let svg=`<svg width="${count*colW}" height="${maxH}" viewBox="0 0 ${count*colW} ${maxH}" overflow="visible">`;for(let i=0;i<count;i++){const x=i*colW+colW/2,an=`eqCassette${i}`;svg+=`<style>@keyframes ${an}{0%{transform:scaleY(${S[i]}) translateY(${maxH*(1-S[i])*.5}px);}100%{transform:scaleY(1) translateY(0);}}</style><g style="animation:${an} ${D[i]}s ease-in-out infinite alternate;transform-origin:bottom center;transform-box:fill-box;">${shapeFn(x,maxH,i)}</g>`;}return svg+'</svg>';}
function buildCassetteEq(){return eqBase(11,12,48,(x,H,i)=>{const c=`hsl(${38+i*4},${60+i*3}%,${42+i*2}%)`;return `<rect x="${x-4}" y="0" width="8" height="${H}" rx="2" fill="${c}" opacity="0.7"/><rect x="${x-5}" y="${H*.3}" width="10" height="3" rx="1" fill="${c}" opacity="0.5"/><rect x="${x-5}" y="${H*.6}" width="10" height="3" rx="1" fill="${c}" opacity="0.5"/>`;});}
function clearState(){frameLayer.classList.remove('show','hide');titleMain.classList.remove('show','hide');titleRow.classList.remove('show','hide');subLayer.classList.remove('show','hide');bottomBar.classList.remove('show');tapeLike.classList.remove('active');tapeBell.classList.remove('active');}
function applyPhase(t){clearState();if(t>=.4&&t<10)frameLayer.classList.add('show');if(t>=1&&t<5){titleMain.classList.add('show');titleRow.classList.add('show');}else if(t>=5){titleMain.classList.add('hide');titleRow.classList.add('hide');}if(t>=5&&t<10){subLayer.classList.add('show');tapeLike.classList.add('active');tapeBell.classList.add('active');}else if(t>=10){subLayer.classList.add('hide');}if(t>=10)bottomBar.classList.add('show');}
function loop(){const start=performance.now();function tick(now){applyPhase(((now-start)/1000)%12);requestAnimationFrame(tick);}requestAnimationFrame(tick);}
frameSvg.innerHTML=buildCassetteFrame();buildCassetteParticles(particles);eqWrap.innerHTML=buildCassetteEq();loop();
